language: csharp
sudo: required
mono:
  - 4.0.5
os:
  - linux
  - osx
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install icu4c; fi
script:
  - ./build.sh --quiet verify
